FROM python:3.12-bullseye

WORKDIR /app


# 依存関係
COPY requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

# アプリコード
COPY . .


EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
